### ISSUE TITLE
https와 cors 과제

### ISSUE THREAD

**Issue by kaswhy** [likelion-Inha-12/kaswhy#13]
https://velog.io/@kaswhy/https%EC%99%80-cors-%EC%84%A4%EC%A0%95

<img width="523" alt="멋사 과제" src="https://github.com/likelion-Inha-12/kaswhy/assets/112332952/c21e6683-88db-4bcf-bc06-f30165a4de5e">

**Comment by juwon0403** [comment]
1) 같은 출처? 다른 출처? 과제 제시 부분에서 포트 번호는 언급되지 않았지만, 출처 확인할 때  포트번호까지 반드시 확인해줘야 한다는 거! 포트가 명시되어 있지 않다면 프로토콜의 기본 포트 번호(http의 기본 포트는 80, https의 기본 포트는 443)를 사용한다는 것도 알고 있으면 좋을 것 같아용
2) Access-Control-Allow-Origin에 모든 출처를 허용한다면 보안상 문제가 생기겠죠?? 모든 출처를 허용하는 것이 좋을지 나쁠지에 대해서도 더 고민해본다면 도움이 될 거예요!

깜찍하게 정리 잘해주셨어요 ㅎㅎ
과제하느라 수고 많으셨습니당~~
